name="Wild Duck Mail"

title="wildduck-www"

[service]
    # email domain for new users
    domain="dapbox.io"
    # default quotas for new users
    quota=1024
    recipients=2000
    forwards=2000
    identities=10
    allowIdentityEdit=true
    allowJoin=true
    enableSpecial=false # if true the allow creating addresses with special usernames
    # allowed domains for new addresses
    domains=["localhost"]

[api]
    url="http://127.0.0.1:8088"
    accessToken=""

[dbs]
    # mongodb connection string for the main database
    mongo="mongodb://127.0.0.1:27017/archive"

    # redis connection string for Express sessions
    redis="redis://127.0.0.1:6379/5"

[www]
    host=false
    port=4000
    proxy=false
    postsize="5MB"
    log="dev"
    secret="a cat"
    secure=false
    listSize=20

[recaptcha]
    enabled=false
    siteKey=""
    secretKey=""

[totp]
    # Issuer name for TOTP, defaults to config.name
    issuer=false
    # once setup do not change as it would invalidate all existing 2fa sessions
    secret="a secret cat"

[u2f]
    # set to false if not using HTTPS
    enabled=true
    # must be https url or use default
    #appId="https://127.0.0.1:8088"

[log]
    level="silly"
    mail=true

[setup]
    # these values are shown in the configuration help page
    [setup.imap]
        hostname="imap.ionos.fr"
        secure=true
        port=993
    [setup.pop3]
        hostname="mail.ionos.fr"
        secure=true
        port=9995
    [setup.smtp]
        hostname="smtp.ionos.fr"
        secure=false
        port=587
